import { PGlite } from "@electric-sql/pglite";
import { readFileSync } from "fs";
const db = new PGlite();
const log:string[]=[];
const ok=async(n:string,q:string)=>{try{await db.exec(q);log.push("PASS "+n);}catch(e:any){log.push("FAIL "+n+": "+e.message);}};
const bad=async(n:string,q:string,re:RegExp)=>{try{await db.exec(q);log.push("FAIL "+n+": kein Fehler");}catch(e:any){log.push((re.test(e.message)?"PASS ":"FAIL ")+n+" -> "+e.message);}};
await db.exec(`create role anon; create role authenticated; create role service_role;
create schema auth; create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
create type public.app_role as enum('admin','patient');
create table public.user_roles(user_id uuid, role app_role);
create function public.has_role(_u uuid,_r app_role) returns boolean language sql stable security definer as $$ select exists(select 1 from public.user_roles where user_id=_u and role=_r) $$;
grant usage on schema auth, public to authenticated; grant execute on function auth.uid() to authenticated;
create function public.update_updated_at_column() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
insert into public.user_roles values('00000000-0000-0000-0000-00000000000a','admin');`);
await db.exec(readFileSync("/dev-server/supabase/migrations/20260728090000_create_kb_phase1_core.sql","utf8"));
await db.exec(`insert into kb_entity_types(code,label) values('product','P'),('product_variant','PV'),('pharmacy','A'),('manufacturer','M') on conflict do nothing;
insert into kb_relation_types(code,label) values('manufactured_by','hergestellt von') on conflict do nothing;
insert into kb_relation_type_domains values('manufactured_by','product','manufacturer','draft') on conflict do nothing;
update kb_relation_type_domains set review_status='approved' where review_status='draft';`);
const A=readFileSync("/dev-server/docs/wiki/vernetzung-migration-A.sql","utf8");
await ok("1 Erstlauf inkl. COMMIT-Constraint-Trigger",A);
await ok("2 Wiederholter Lauf (idempotent)",A);
await ok("3 Dritter Lauf",A);
const r=await db.query(`select (select count(*) from kb_relation_type_domains where relation_type_code='offered_by') d,(select is_active from kb_relation_types where code='offered_by') a,(select count(*) from pg_policies where tablename='kb_source_actors') p`);
log.push("INFO Domänen/aktiv/Policies nach 3 Läufen: "+JSON.stringify(r.rows[0]));
await bad("4 Alter Fehler reproduziert: offered_by aktiv ohne approved Domäne",`begin; update kb_relation_types set is_active=true where code='offered_by'; commit;`,/approved domain/);
await db.exec("rollback").catch(()=>{});
await bad("5 Strukturprüfung erkennt abweichende Tabelle",`begin; alter table kb_source_actors add column x int; ${A.replace(/^BEGIN;|COMMIT;\s*--[\s\S]*$/gm,"")}`,/abweichender Struktur/);
await db.exec("rollback").catch(()=>{});
await bad("6 Teilinsert bei Fehler zurückgerollt (Transaktion)",`begin; insert into kb_entity_types(code,label) values('zz_tmp','x'); select 1/0; commit;`,/division/);
await db.exec("rollback").catch(()=>{});
const z=await db.query(`select count(*) c from kb_entity_types where code='zz_tmp'`); log.push((z.rows[0] as any).c==0?"PASS 6b kein Rest":"FAIL 6b Rest vorhanden");
await db.exec(`insert into kb_entities(id,canonical_key,entity_type_code) values('10000000-0000-0000-0000-000000000001','pharmacy:test','pharmacy');
insert into kb_sources(id,canonical_key) values('20000000-0000-0000-0000-000000000001','src:test');
insert into kb_source_revisions(source_id,revision_no,source_type,title,content_hash) values('20000000-0000-0000-0000-000000000001',1,'website','T',repeat('a',64));`).catch(e=>log.push("SETUP entity: "+e.message));
const src=await db.query(`select column_name from information_schema.columns where table_name='kb_source_revisions' and is_nullable='NO' and column_default is null`); log.push("INFO Pflichtfelder source_revisions: "+src.rows.map((x:any)=>x.column_name).join(","));
await db.exec(`set test.uid='00000000-0000-0000-0000-00000000000a'; set role authenticated;`);
await ok("7a Admin legt Draft an (Spaltengrants)",`insert into kb_source_actors(source_revision_id,entity_id,role,locator,original_quote) select id,'10000000-0000-0000-0000-000000000001','pharmacy','Impressum Z.3','Blumenau-Apotheke' from kb_source_revisions limit 1;`);
await bad("7b Direktes approved per UPDATE",`update kb_source_actors set review_status='approved'`,/permission/);
await bad("7c approved per INSERT",`insert into kb_source_actors(source_revision_id,entity_id,role,locator,review_status) select id,'10000000-0000-0000-0000-000000000001','author','x','approved' from kb_source_revisions limit 1;`,/permission/);
await bad("8 GUC gesetzt + Statuswrite (Bypassversuch)",`select set_config('kb.source_actor_review','on',false); update kb_source_actors set review_status='approved';`,/permission/);
await bad("9 Review ohne Notiz",`select kb_review_source_actor((select id from kb_source_actors limit 1),'approved','')`,/Pflicht/);
await ok("10 Review mit Notiz",`select kb_review_source_actor((select id from kb_source_actors limit 1),'approved','BfArM-Register geprüft')`);
await bad("11 Geprüfte Fundstelle ändern",`update kb_source_actors set locator='neu'`,/unveraenderlich/);
await bad("12 Geprüfte Zuordnung löschen",`delete from kb_source_actors`,/nicht loeschbar/);
await ok("13 Rücknahme = withdrawn (Historie bleibt)",`select kb_review_source_actor((select id from kb_source_actors limit 1),'withdrawn','Rücknahme Test')`);
await bad("14 withdrawn erneut ändern",`select kb_review_source_actor((select id from kb_source_actors limit 1),'approved','x')`,/unveraenderlich/);
await ok("15 Neue Zuordnung nach Rücknahme (supersedes)",`insert into kb_source_actors(source_revision_id,entity_id,role,locator,supersedes_id) select source_revision_id,entity_id,role,'Z.4',id from kb_source_actors limit 1;`);
const h=await db.query(`select review_status from kb_source_actors order by created_at`); log.push("INFO Historie: "+h.rows.map((x:any)=>x.review_status).join(" -> "));
await db.exec(`reset role; set test.uid='00000000-0000-0000-0000-00000000000b'; set role authenticated;`);
await bad("16 Nicht-Admin Review",`select kb_review_source_actor((select id from kb_source_actors where review_status='draft' limit 1),'approved','x')`,/Nur Admin|permission/);
await db.exec(`reset role`);
await db.exec(`insert into kb_entity_types(code,label) values('symptom','S') on conflict do nothing;
insert into kb_entities(id,canonical_key,entity_type_code) values('10000000-0000-0000-0000-000000000002','symptom:x','symptom');`);
const ac=await db.query(`select column_name from information_schema.columns where table_name='kb_assertions' and is_nullable='NO' and column_default is null`); log.push("INFO Pflichtfelder assertions: "+ac.rows.map((x:any)=>x.column_name).join(","));
const as=await db.query(`select count(*) c from information_schema.columns where table_name='kb_assertions' and column_name='polarity'`); log.push(((as.rows[0] as any).c==0?"PASS":"FAIL")+" 17 kb_assertions unverändert (keine Pauschal-Polarity)");
console.log(log.join("\n"));
