import { EXTRA_CHECKS } from "./infothekDecisions";
/**
 * Registry of HTML comparison reviews. One shared view (InfothekHtmlVergleich) serves all articles.
 * Decisions stay browser-local per slug (storage key unchanged for krankheit-ist-messbar).
 */
import { KRANKHEIT_IST_MESSBAR_CHANGES, CHANGE_TOPICS as KIM_TOPICS, UNMARKED_NOTES as KIM_NOTES, type ComparisonChange } from "@/lib/infothekComparisonChanges";
import kimDraft from "../../website-content/infothek/drafts/krankheit-ist-messbar.entwurf.html?raw";
import allergieDraft from "../../website-content/infothek/drafts/allergiebehandlung.entwurf.html?raw";
import kieferBase from "../../website-content/infothek/drafts/kieferostitis.basis.html?raw";
import assDraft from "../../website-content/infothek/drafts/ass-salicylat-histamin.entwurf.html?raw";
import diabDraft from "../../website-content/infothek/drafts/diabetes-handout.entwurf.html?raw";
import ersttDraft from "../../website-content/infothek/drafts/ersttermin-naturheilpraxis.entwurf.html?raw";
import twDraft from "../../website-content/infothek/drafts/therapieweg-uebersicht.entwurf.html?raw";
import candidaDraft from "../../website-content/infothek/drafts/candida-diaet.entwurf.html?raw";
import siboDraft from "../../website-content/infothek/drafts/sibo-duenndarmfehlbesiedlung.entwurf.html?raw";
import burnoutDraft from "../../website-content/infothek/drafts/muedigkeit-erschoepfung-burnout.entwurf.html?raw";
import kraeuterDraft from "../../website-content/infothek/drafts/kraeuter-schmerz-entzuendung.entwurf.html?raw";
import kieferDraft from "../../website-content/infothek/drafts/kieferostitis.entwurf.html?raw";
import dankDraft from "../../website-content/infothek/drafts/dankbarkeit-alltag.entwurf.html?raw";
import umweltDraft from "../../website-content/infothek/drafts/umwelt-alltag-gesundheit.entwurf.html?raw";
import vievaDraft from "../../website-content/infothek/drafts/vieva-pro-vitalanalyse.entwurf.html?raw";
import zapperDraft from "../../website-content/infothek/drafts/zapper-diamond-shield.entwurf.html?raw";
import logiDraft from "../../website-content/infothek/drafts/logi-ernaehrung-mitochondrien.entwurf.html?raw";
import mitoDraft from "../../website-content/infothek/drafts/mitochondropathie-hws.entwurf.html?raw";
import parasDraft from "../../website-content/infothek/drafts/parasiten-deutschland.entwurf.html?raw";
import virenDraft from "../../website-content/infothek/drafts/viren-bakterien-deutschland.entwurf.html?raw";

export interface ComparisonConfig {
  slug: string;
  heading: string;
  /** Left side: currently delivered original (edge function) or – for new articles – a local base draft. */
  base: { kind: "delivered"; route: string } | { kind: "baseDraft"; html: string };
  leftLabel: string;
  draftHtml: string;
  changes: ComparisonChange[];
  topics: Record<number, string>;
  notes: string[];
  /** Article-specific open checks not covered by numbered proposals. */
  extraChecks: string[];
  /** Title used in the progress report. */
  reportTitle: string;
  /** Only the first article has the naming table. */
  naming?: boolean;
}

const KIEFER: ComparisonChange[] = [
  { id: 1, reason: ["SEO"], note: "HTML-Seitentitel", headOnly: { kind: "title", before: "Kieferostitis | Naturheilpraxis Rauch", after: "Kieferostitis verstehen: Kieferknochen, Entzündung und Erreger | Heilpraktiker Peter Rauch Augsburg" }, why: "Der Titel nennt Thema, Inhalt und Praxis – das ist für Leser und Suchmaschinen eindeutig." },
  { id: 2, reason: ["SEO"], note: "Meta-Beschreibung", headOnly: { kind: "description", before: "Information zur Kieferostitis.", after: "Kieferostitis und Kieferosteomyelitis verständlich erklärt: Formen, typische Erreger, Abklärung beim Zahnarzt/MKG und naturheilkundliche Behandlung in der Praxis Peter Rauch, Augsburg." }, why: "Die Kurzbeschreibung fasst den Artikel sachlich und positiv zusammen, ohne Heilversprechen." },
  { id: 3, reason: ["Lesbarkeit", "SEO"], note: "H1 = Arbeitstitel", orig: "Kieferostitis: Entzündung im Kieferknochen", draft: "Kieferostitis verstehen: Kieferknochen, Entzündung und Erreger", why: "Die Überschrift greift den Arbeitstitel auf und kündigt alle drei Schwerpunkte an." },
  { id: 4, reason: ["Inhalt/Recht"], note: "Häufigkeit an die konkrete Studie gebunden", orig: "In Studien am häufigsten nachgewiesen.", draft: "kanadischen Auswertung über zehn Jahre", why: "„In Studien“ klang allgemeingültig. Jetzt steht die Aussage genau bei der Quelle (37 Fälle, Proben von 33) – ohne Prozentwerte, die sich nicht übertragen lassen." },
  { id: 5, reason: ["Inhalt/Recht"], note: "Praxisangebot eigenständig beschrieben", orig: "Ich unterstütze Sie naturheilkundlich.", draft: "Als Heilpraktiker behandle ich Sie in meiner Praxis", why: "Beschreibt Peters eigene naturheilkundliche Behandlung positiv und wahr – ohne pauschale Unterordnung. Die zahnärztliche/MKG-Herdsanierung steht dort, wo sie medizinisch hingehört (Abschnitt Behandlung)." },
  { id: 6, reason: ["SEO"], note: "Echte interne Links ergänzt", orig: "0821-2621462 · Friedrich-Deffner-Str. 19a", draft: "Weiterlesen:", insertAfter: "self", draftWrap: "nav", why: "Links zu vorhandenen Praxisseiten (Ersttermin, Therapieweg, Viren und Bakterien) helfen Lesern weiter." },
  { id: 7, reason: ["Inhalt/Recht"], note: "Neuer Abschnitt: Kieferhöhle/Nasennebenhöhlen als Nachbarherd", orig: "Welche Erreger eine Rolle spielen", draft: "Kieferhöhle und Nasennebenhöhlen als Nachbarn", insertAfter: "parentNext", draftWrap: "section", why: "Peters Nachtrag: beide Richtungen getrennt. Zahn → Kieferhöhle ist im Expertenkonsens (Int J Oral Sci 2024) beschrieben; Kieferhöhle → Oberkieferknochen nur in seltenen Fallberichten – keine Häufigkeit, kein typischer Erreger, keine Übertragung auf den Unterkiefer. Schleimhautverdickung allein beweist keinen Knochenherd. Kein neues Behandlungsangebot." },
  { id: 8, reason: ["Inhalt/Recht"], note: "Neuer Hinweis: Enteroviren als offene Forschungsfrage", orig: "RANTES/CCL5 ist ein Entzündungsbotenstoff", draft: "Offene Forschungsfrage: Enteroviren", insertAfter: "self", draftWrap: "div", why: "Ergebnis der Enteroviren-Recherche: Knochenbefunde gibt es nur im Mausmodell (Roberts/Boyd 1987, Lee 2013). Eine klinische Studie am menschlichen Kiefer wurde nicht gefunden – das steht als Recherchegrenze da, nicht als Unmöglichkeit. Keine Testempfehlung, kein antivirales Wirkversprechen; Lechner 2017 hat keine Enterovirus-RNA untersucht und wird deshalb hier nicht angeführt." },
  { id: 9, reason: ["Inhalt/Recht"], note: "Formen: nicht-bakterielle Osteomyelitis eigene Gruppe", orig: "Nicht-bakterielle Formen", draft: "Nicht-bakterielle Form", withNext: true, why: "Astra: Die primär chronische nicht-bakterielle Osteomyelitis braucht eine eigene fachärztliche Therapieentscheidung (Fallserie PMID 31941491). Strahlen-/medikamentenbedingte Osteonekrose wird als eigene Gruppe abgegrenzt – nicht pauschal nicht-bakteriell, eine bakterielle Begleitinfektion ist möglich (AWMF 007-046)." },
  { id: 10, reason: ["Inhalt/Recht"], note: "Herdbehandlung auf bakterielle/odontogene Formen begrenzt", orig: "Die Behandlung richtet sich nach der Ursache.", draft: "Die Behandlung richtet sich nach der Ursache.", why: "Die chirurgische Herdbehandlung gilt für bakterielle, insbesondere vom Zahn ausgehende Formen; nicht-bakterielle Formen und Osteonekrosen werden fachärztlich eigenständig beurteilt." },
  { id: 11, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Überschrift: Behandlung statt Begleitung", orig: "Naturheilkundliche Begleitung in meiner Praxis", draft: "Naturheilkundliche Behandlung in meiner Praxis", why: "Peter ist selbst der behandelnde Heilpraktiker; die Überschrift beschreibt sein Angebot eigenständig." },
  { id: 12, reason: ["Inhalt/Recht"], note: "Listenpunkt ohne pauschalen Abstimmungszusatz", orig: "abgestimmt auf Ihre laufende Behandlung", draft: "naturheilkundliche Behandlung mit Blick auf", why: "Pauschaler Zusatz entfernt; das Angebot wird eigenständig und ohne Wirkversprechen beschrieben." },
];

const ALLERGIE: ComparisonChange[] = [
  { id: 1, reason: ["SEO"], note: "HTML-Seitentitel", headOnly: { kind: "title", before: "Allergiebehandlung in der Naturheilpraxis | Heilpraktiker Rauch Augsburg", after: "Allergien verstehen und naturheilkundlich begleiten | Heilpraktiker Peter Rauch Augsburg" }, why: "„Allergiebehandlung“ kann als Behandlungsversprechen gelesen werden; „verstehen und begleiten“ beschreibt den Inhalt genauer." },
  { id: 2, reason: ["SEO", "Inhalt/Recht"], note: "Meta-Beschreibung", headOnly: { kind: "description", before: "Ganzheitliche Allergiebehandlung in der Naturheilpraxis Peter Rauch Augsburg: Allergie-Typen, Diagnostik, Naturheilkunde, Orthomolekulare Therapie, TCM und Psychosomatik.", after: "Allergien verständlich erklärt: Allergie-Typen, Symptome, schulmedizinische Behandlung und naturheilkundliche Begleitung in der Naturheilpraxis Peter Rauch, Augsburg-Hochzoll." }, why: "Nennt, was öffentlich sichtbar ist; die geschützten Praxisabschnitte werden nicht als frei zugänglicher Inhalt angekündigt." },
  { id: 3, reason: ["Lesbarkeit"], note: "Einladende Unterzeile statt Pauschal-Disclaimer", orig: "Informationsmaterial – kein Heilversprechen gemäß HWG", draft: "Patienteninformation der Naturheilpraxis Peter Rauch", why: "Der rechtliche Hinweis steht ausführlich am Ende. Auf der Titelfolie wirkt er abschreckend." },
  { id: 4, reason: ["Inhalt/Recht"], note: "Prozentangabe nur mit Primärquelle", orig: "Schätzungsweise 20–30 % der europäischen Bevölkerung", draft: "häufigsten chronischen Gesundheitsproblemen", why: "Die Zahl stammt aus einem Sekundärwerk und Wikipedia. Ohne Primärquelle ist die allgemeine Aussage sicherer; mit belegter Quelle kann die Zahl bleiben – Peters Entscheidung." },
  { id: 5, reason: ["Inhalt/Recht"], note: "Metatron-Hospital in meiner Therapieplanung", orig: "Metatron-Analyse – biophysikalisches Analyseverfahren", draft: "Metatron-Hospital-Analyse – ein zentraler Baustein", why: "Beschreibt Peters tatsächliche Arbeitsweise und den Stellenwert der Analyse in seiner Therapieplanung, ohne einen wissenschaftlichen Diagnosenachweis oder garantierten Erfolg zu behaupten." },
  { id: 6, reason: ["Inhalt/Recht"], note: "Austestung der Erfahrungsheilkunde zugeordnet", orig: "Kinesiologisch-frequenztherapeutische Austestung", draft: "Kinesiologische und frequenzbasierte Austestung", why: "Verständlicher und klar als Erfahrungsheilkunde gekennzeichnet." },
  { id: 7, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Labor: übliche Allergieparameter genannt", orig: "Labordiagnostik – konventionelle Blutanalyse", draft: "Gesamt-IgE und spezifisches IgE", why: "Nennt die konventionell üblichen Allergie-Laborwerte und zeigt, dass die Praxis auch schulmedizinische Befunde nutzt." },
  { id: 8, reason: ["Inhalt/Recht"], note: "EAV als Begleitung statt „Allergie-Behandlung“", orig: "EAV-Allergie-Behandlung", draft: "Elektroakupunktur nach Voll (EAV) als Begleitung", why: "„Allergie-Behandlung“ verspricht eine Behandlung der Allergie durch EAV. „Als Begleitung“ beschreibt das Angebot ohne Wirkversprechen." },
  { id: 9, reason: ["Inhalt/Recht"], note: "Individuelle naturheilkundliche Behandlung in meiner Praxis", orig: "mit individueller Diagnostik, Beratung und naturheilkundlicher Unterstützung.", draft: "Darauf aufbauend plane ich mit Ihnen die naturheilkundliche Behandlung", why: "Beschreibt Peters eigene Behandlung positiv: Gespräch über Allergiegeschehen, Beschwerden und Verlauf, darauf aufbauend die Planung. Ohne Wirk- oder Diagnoseversprechen." },
  { id: 10, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Überschrift: Analyse und Therapieplanung", orig: "Diagnostik in der Naturheilpraxis", draft: "Analyse und Therapieplanung in meiner Praxis", why: "Kontext zu Vorschlag 5: beschreibt die Praxisrolle (Analyse und Planung) statt einer Diagnoseleistung." },
  { id: 11, reason: ["Inhalt/Recht"], note: "Einleitung: individuelle Planung", orig: "zur Allergie-Abklärung eingesetzt", draft: "plane ich Ihre naturheilkundliche Behandlung individuell", why: "Ersetzt die pauschale Allergie-Abklärungsbehauptung. Vorhandene Befunde und bisheriger Verlauf werden optional einbezogen – keine Pflicht einer vorherigen ärztlichen Behandlung, keine Überlegenheit oder Ursachenfindung." },
  { id: 12, reason: ["Inhalt/Recht"], note: "Zwischenüberschrift: Bausteine meiner Analyse", orig: "Diagnostische Möglichkeiten:", draft: "Bausteine meiner Analyse:", why: "Passt zu Vorschlag 10; leitet keine Diagnoseleistung aus der Praxisrolle ab. Laborwerte bleiben als konventionelle Befunde getrennt benannt." },
];


const ASS: ComparisonChange[] = [
  { id: 1, reason: ["SEO", "Inhalt/Recht"], note: "Meta-Beschreibung mit Praxisangebot", headOnly: { kind: "description", before: "Umfassender Patientenratgeber: ASS-Intoleranz, Salicylat- und Histamin-Unverträglichkeit verständlich erklärt. Heilpraktiker Peter Rauch, Augsburg.", after: "ASS-Intoleranz, Salicylat- und Histamin-Unverträglichkeit verständlich erklärt: Auslöser, Ernährung, Alltagstipps und naturheilkundliche Behandlung in der Naturheilpraxis Peter Rauch, Augsburg." }, why: "Nennt die tatsächlichen Inhalte und das Praxisangebot – hilft Suchenden, die passende Seite zu finden." },
  { id: 2, reason: ["Inhalt/Recht"], note: "Praxisangebot ohne pauschale Unterordnung", orig: "Wir ergänzen die schulmedizinische Behandlung.", draft: "Darauf aufbauend plane ich mit Ihnen die naturheilkundliche Behandlung", why: "Praxisrollenstandard: Peter ist selbst der behandelnde Heilpraktiker; Angebot eigenständig und ohne Wirkversprechen beschrieben." },
  { id: 3, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Überschrift: Behandlung statt Begleitung", orig: "Naturheilkundliche Begleitung:", draft: "Naturheilkundliche Behandlung in meiner Praxis:", why: "Praxisrollenstandard: Peter ist selbst der behandelnde Heilpraktiker; Angebot eigenständig und ohne Wirkversprechen beschrieben." },
  { id: 4, reason: ["Inhalt/Recht"], note: "Metatron-Hospital in meiner Therapieplanung", orig: "Verfahren der Erfahrungsheilkunde – kein Ersatz für schulmedizinische Diagnostik", draft: "Verfahren der Erfahrungsheilkunde – ein zentraler Baustein meiner Therapieplanung", why: "Beschreibt den Stellenwert der Analyse in Peters Arbeitsweise. Die Einordnung als Erfahrungsheilkunde (nicht durch RCTs belegt) bleibt im Hinweisabsatz direkt darunter erhalten." },
  { id: 5, reason: ["Lesbarkeit"], note: "Pflanzliche Unterstützung", orig: "Pflanzliche Begleitung bei Unverträglichkeitsreaktionen", draft: "Pflanzliche Unterstützung bei Unverträglichkeitsreaktionen", why: "Klarer als „Begleitung“. „Unterstützung“ beschreibt den Einsatz pflanzlicher Mittel, ohne eine Heilwirkung zu versprechen; eine rechtliche Prüfung des Gesamttexts nach HWG ersetzt die Formulierung nicht." },
  { id: 6, reason: ["Inhalt/Recht"], note: "Samter-Trias vollständig: NSAR-Reaktion als drittes Merkmal", orig: "Nasenpolypen", draft: "Chronische Rhinosinusitis mit Nasenpolypen", withNext: true, why: "Die Trias (AERD) besteht aus Asthma, chronischer Rhinosinusitis mit Nasenpolypen und der Atemwegsreaktion auf ASS/COX-1-hemmende NSAR (AAAAI, aaaai.org – AERD). Polypen und Rhinosinusitis waren getrennt gezählt, das dritte Merkmal fehlte." },
  { id: 7, reason: ["Inhalt/Recht"], note: "Lebensmittelampel: Lachs widerspruchsfrei", orig: "Frischer Lachs, Rind", draft: "Gelagerter oder geräucherter Lachs", why: "Die Detailtabelle führt frischen Lachs als histaminarm, die Übersicht als „hoch“. Histamin entsteht bei Lagerung/Verderb (Comas-Basté et al., PMC8511827); daher gelagert/geräuchert = hoch, fangfrisch = niedrig. Pils (Detail grün, Übersicht „mittel“) bleibt offen für Peter." },
  { id: 8, reason: ["Inhalt/Recht"], note: "Spirituosen nicht pauschal verträglich", orig: "Nur destillierte klare Spirituosen", draft: "Klare Spirituosen enthalten meist wenig Histamin", why: "Alkohol kann den Histaminabbau hemmen; Verträglichkeit hängt von Menge, Begleitspeisen und individueller Reaktion ab (PMC8511827). „Nur Spirituosen“ wirkte wie eine Freigabe." },
];
const DIAB: ComparisonChange[] = [
  { id: 1, reason: ["Lesbarkeit"], note: "Einladende Unterzeile statt Pauschal-Disclaimer", orig: "Informationsmaterial – kein Heilversprechen gemäß HWG", draft: "Patienteninformation der Naturheilpraxis Peter Rauch", why: "Der rechtliche Hinweis steht ausführlich am Ende; auf der Titelfolie wirkt er abschreckend." },
  { id: 2, reason: ["Inhalt/Recht"], note: "Studienbeleg konkret benannt", orig: "(Studien belegt!)", draft: "senkt das Risiko nachweislich (DCCT, UKPDS)", why: "Statt eines pauschalen Ausrufs werden die im Handout bereits genannten Studien (DCCT 1993, UKPDS 1998) als Beleg für den Zusammenhang Blutzuckereinstellung–Komplikationen genannt." },
  { id: 3, reason: ["Inhalt/Recht"], note: "Spaziergang ohne unbelegte 30-%-Zahl", orig: "bis zu 30 % senken", draft: "spürbar abflachen", why: "Kurze Spaziergänge nach dem Essen senken den Blutzuckeranstieg (z. B. DiPietro et al., Diabetes Care 2013). Eine allgemeine „bis zu 30 %“-Zahl ist nicht mit Primärquelle belegt; mit Quelle kann sie bleiben – Peters Entscheidung." },
  { id: 4, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Überschrift: Behandlung statt Begleitung", orig: "Naturheilkundliche Begleitung", draft: "Naturheilkundliche Behandlung in meiner Praxis", why: "Praxisrollenstandard: Peter ist selbst der behandelnde Heilpraktiker; Angebot eigenständig und ohne Wirkversprechen beschrieben." },
  { id: 5, reason: ["Inhalt/Recht"], note: "Typ 2: Insulin nicht bei allen", orig: "Erst im späteren Verlauf", draft: "Nicht immer – nur wenn Lebensstil", why: "Viele Menschen mit Typ 2 kommen ohne Insulin aus; die NVL Typ-2-Diabetes sieht eine stufenweise, individuelle Therapie vor (leitlinien.de, Version 3, Kap. 5)." },
  { id: 6, reason: ["Inhalt/Recht"], note: "Medikamentenliste: Insulin bei Typ 2 nur bei Bedarf", orig: "bei Typ 2 im Verlauf", draft: "bei Typ 2 nur bei Bedarf", why: "Wie Vorschlag 5." },
  { id: 7, reason: ["Inhalt/Recht"], note: "Zielwerte als Orientierung, persönlicher Zielbereich", orig: "sicherer Zielwert", draft: "Ihren persönlichen Zielbereich", why: "NVL Typ-2-Diabetes, Empfehlung 5-8 (bestätigt 2023): individualisierte HbA1c-Ziele nach Alter, Begleiterkrankungen, Therapie und Unterzuckerrisiko. Die Tabellenwerte bleiben als Orientierung." },
  { id: 8, reason: ["Inhalt/Recht"], note: "Messplan als Orientierung", orig: "Wie oft messen?", draft: "Die Tabelle ist eine Orientierung", insertAfter: "self", draftWrap: "p", why: "Ein universeller Messplan passt nicht für jede Therapie (ohne Insulin oft deutlich weniger Messungen); Hinweis auf individuelle Festlegung." },
  { id: 9, reason: ["Inhalt/Recht"], note: "DCCT/UKPDS korrekt wiedergegeben: Gesamttherapie, Studienzahlen", orig: "Die DCCT- und UKPDS-Studien belegen", draft: "In der UKPDS senkte eine intensivere", why: "Quellen gelesen 07.10.2026: UKPDS (dtu.ox.ac.uk/UKPDS): HbA1c 7,0 vs. 7,9 % über median 10 Jahre mit Sulfonylharnstoff/Insulin → mikrovaskulär −25 %, diabetesbezogene Endpunkte −12 %. DCCT (repository.niddk.nih.gov/study/159): Typ 1, intensive vs. konventionelle Insulintherapie → Retino-, Nephro-, Neuropathie verlangsamt. Beide vergleichen Therapiestrategien, nicht Selbstmessung allein. Die bisherige „35 % je 1 %“-Zahl steht auf keiner der beiden Seiten (stammt aus einer UKPDS-Beobachtungsauswertung) und wurde ersetzt." },
  { id: 10, reason: ["Inhalt/Recht"], note: "Metatron: Hinweise statt Identifikation", orig: "Identifikation von Belastungsfaktoren", draft: "Hinweise auf mögliche Belastungsfaktoren", why: "Metatron bleibt zentraler Baustein der Therapieplanung; ein konkreter Nachweis von Schwermetallen/Infektionen bräuchte eine eigene Quelle bzw. Laborbestimmung." },
];
const ERSTT: ComparisonChange[] = [
  { id: 1, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Vorgespräch: passt die Behandlung?", orig: "ob eine naturheilkundliche Begleitung grundsätzlich passend erscheint", draft: "ob eine naturheilkundliche Behandlung in meiner Praxis zu Ihrem Anliegen passt", why: "Praxisrollenstandard: Peter ist selbst der behandelnde Heilpraktiker; Angebot eigenständig und ohne Wirkversprechen beschrieben." },
  { id: 2, reason: ["Inhalt/Recht"], note: "Sicherheit konkret statt pauschaler Unterordnung", orig: "Naturheilkundliche Begleitung versteht sich nicht als Ersatz für notwendige ärztliche Diagnostik oder Behandlung.", draft: "Ist eine weitere ärztliche oder fachärztliche Abklärung medizinisch notwendig, spreche ich das offen an.", why: "Die Sicherheitsaussage bleibt im passenden Abschnitt („Sicherheit geht vor“), aber als konkrete Zusage statt pauschaler Unterordnung." },
  { id: 3, reason: ["Lesbarkeit"], note: "Analyse- und Behandlungsoptionen", orig: "Mögliche Untersuchungs- oder Begleitungsoptionen verständlich erläutern.", draft: "Mögliche Analyse- und Behandlungsoptionen verständlich erläutern.", why: "Praxisrollenstandard: Peter ist selbst der behandelnde Heilpraktiker; Angebot eigenständig und ohne Wirkversprechen beschrieben." },
  { id: 4, reason: ["Inhalt/Recht"], note: "FAQ: ärztliche Behandlung läuft weiter", orig: "Naturheilkundliche Begleitung kann eine ärztliche Versorgung ergänzen, ersetzt sie aber nicht.", draft: "Eine bestehende ärztliche Behandlung läuft weiter, und ich beziehe sie in die Planung ein.", why: "Beantwortet die Frage direkt und positiv; die Medikamenten-Sicherheitsaussage bleibt erhalten (Einzelfallkontext)." },
];
const TW: ComparisonChange[] = [
  { id: 1, reason: ["Inhalt/Recht"], note: "Überschrift: Analyse statt Diagnostik (Metatron)", orig: "Diagnostik: Metatron Hospital System", draft: "Analyse: Metatron Hospital System", why: "Wie bei Allergie Vorschlag 10: beschreibt die Praxisrolle als Analyse und Therapieplanung, ohne eine schulmedizinische Diagnoseleistung zu behaupten." },
  { id: 2, reason: ["Inhalt/Recht"], note: "Metatron-Hospital in meiner Therapieplanung", orig: "Es ist wissenschaftlich und schulmedizinisch nicht anerkannt.", draft: "ein zentraler Baustein meiner Therapieplanung", why: "Stellenwert in Peters Arbeitsweise positiv benannt; die Einordnung (Erfahrungsheilkunde, keine schulmedizinische Diagnose) bleibt im Satz, die Nicht-Anerkennung steht bereits im Eingangs- und Schlusshinweis." },
  { id: 3, reason: ["Inhalt/Recht"], note: "Überschrift: Analyse (Trikombin & Vieva)", orig: "Diagnostik: Trikombin & Vieva Plus", draft: "Analyse: Trikombin & Vieva Plus", why: "Passt zu Vorschlag 1." },
  { id: 4, reason: ["Inhalt/Recht"], note: "Behandlung auf Grundlage der Analysehinweise", orig: "Gezielte bioenergetische Behandlung der ermittelten Ursachen", draft: "Bioenergetische Behandlung auf Grundlage der in der Analyse gefundenen Hinweise", why: "„Ermittelte Ursachen“ behauptet einen gesicherten Ursachennachweis; „Hinweise“ entspricht der Einordnung der Analyse auf derselben Seite." },
  { id: 5, reason: ["Inhalt/Recht"], note: "FAQ: ärztliche Behandlung läuft weiter", orig: "Die naturheilkundliche Behandlung versteht sich als Ergänzung, nicht als Ersatz für eine ärztliche Behandlung.", draft: "Eine bestehende ärztliche Behandlung läuft weiter, und ich beziehe sie in die Planung ein.", why: "Beantwortet die Frage positiv und eigenständig; Medikamentenhinweis bleibt (Einzelfallkontext)." },
  { id: 6, reason: ["Inhalt/Recht"], note: "Allergien: Testungshinweis, IgG kein Nachweis", orig: "IgE- und IgG-vermittelt", draft: "Hinweise der Testung; ein IgE-Nachweis", why: "Die Liste gehört zur bioenergetischen Testung; „IgE-/IgG-vermittelt“ klang nach Laborbefund. Lebensmittel-IgG zeigt keine Allergie/Unverträglichkeit an (AAAAI, IgG Food Test)." },
  { id: 7, reason: ["Inhalt/Recht"], note: "Therapiesitzungen: Analysehinweise statt ermittelter Belastungen", orig: "ermittelten Belastungen", draft: "auf Grundlage der Analysehinweise", why: "Wie Vorschlag 4: Analysehinweise werden nicht später als gesicherte Ursachen dargestellt." },
  { id: 8, reason: ["Inhalt/Recht"], note: "Übersichtstabelle: Analyse statt Diagnostik", orig: "Gezielte bioenergetische Diagnostik", draft: "Bioenergetische Analyse", why: "Passt zu Vorschlag 1 und 3." },
];


const CAND: ComparisonChange[] = [
  { id: 1, reason: ["Lesbarkeit"], note: "Einladende Unterzeile statt Pauschal-Disclaimer", orig: "Informationsmaterial – kein Heilversprechen gemäß HWG", draft: "Patienteninformation der Naturheilpraxis Peter Rauch", why: "Der rechtliche Hinweis steht ausführlich am Ende; auf der Titelfolie wirkt er abschreckend (wie Allergie/Diabetes Vorschlag 1/3)." },
  { id: 2, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Überschrift: Behandlung statt Begleitung", orig: "Therapeutische Begleitung", draft: "Naturheilkundliche Behandlung in meiner Praxis", why: "Praxisrollenstandard: Peter ist selbst der behandelnde Heilpraktiker; Angebot eigenständig, ohne Wirkversprechen." },
  { id: 3, reason: ["Inhalt/Recht"], note: "Metatron-Hospital in meiner Therapieplanung", orig: "Biophysikalische Analyse und Meta-Therapie bei Verdacht", draft: "Metatron-Hospital-Analyse – ein zentraler Baustein", why: "Metatron-Hospital ist ein zentraler Baustein meiner Therapieplanung; die Analyseergebnisse fließen in die individuelle Behandlungsplanung ein. Ein Pilznachweis wird der Analyse nicht zugeschrieben." },
  { id: 4, reason: ["Inhalt/Recht"], note: "Erfahrungsheilkunde ohne Negativ-Anhang", orig: "kein Ersatz für ärztliche/heilpraktische Behandlung", draft: "Grundlage meiner individuellen Therapieplanung", why: "Wie ASS Vorschlag 4: Die Einordnung als Erfahrungsheilkunde bleibt; der pauschale Negativsatz entfällt. Die ausführliche Einordnung im folgenden Kasten bleibt unverändert." },
  { id: 5, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Überschrift: Beratung & Behandlung", orig: "Beratung & Begleitung", draft: "Beratung & Behandlung in meiner Praxis", why: "Praxisrollenstandard." },
  { id: 6, reason: ["Inhalt/Recht"], note: "Strenge und Dauer individuell statt Zucker-Reaktivierung", orig: "Bereits kleine Mengen Zucker", draft: "Feste Regeln für alle gibt es dafür nicht", why: "Für eine Reaktivierung durch kleine Zuckermengen gibt es keinen klinischen Beleg; individuelle Ernährung nach Beschwerden, Befunden und Verträglichkeit." },
  { id: 7, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "„Verboten“ → „Eher meiden – je nach Verträglichkeit“", orig: "Verbotene Lebensmittel", draft: "Eher meiden – je nach Verträglichkeit", why: "Pauschale Verbote sind nicht belegt; die Liste bleibt als Orientierung." },
  { id: 8, reason: ["Inhalt/Recht"], note: "Obst und Süßungsmittel nach individueller Absprache", orig: "(frisch & getrocknet)", draft: "Auswahl und Menge nach individueller Absprache", withNext: true, why: "Monatelange vollständige Obst-/Süßungsmittelverbote ohne klinischen Beleg; individuelle Festlegung." },
  { id: 9, reason: ["Inhalt/Recht"], note: "Zucker reduzieren statt „vollständig meiden“", orig: "vollständig gemieden", draft: "Zucker deutlich zu reduzieren", why: "Wie Vorschlag 6." },
  { id: 10, reason: ["Inhalt/Recht"], note: "Dauer individuell statt 4–6 Wochen / 3–6 Monate", orig: "mindestens 4–6 Wochen", draft: "Die Dauer der Ernährungsumstellung legen wir", why: "Feste Dauerangaben ohne Beleg; Behandlung in der Praxis bleibt genannt, ohne „begleitend“." },
  { id: 11, reason: ["Inhalt/Recht"], note: "Neue oder zunehmende Beschwerden abklären statt „Pilze sterben ab“ (inkl. Kastenüberschrift)", orig: "Dies kann ein Zeichen sein, dass die Pilze absterben", draft: "Treten während der Umstellung neue oder zunehmende Beschwerden auf", why: "Für eine „Absterbereaktion“ gibt es keinen verlässlichen Beleg; neue/zunehmende Beschwerden werden abgeklärt. Die Kastenüberschrift „Erstverschlimmerung (Herxheimer-Reaktion)“ wird mit ersetzt." },
  { id: 12, reason: ["Inhalt/Recht"], note: "Trikombin: Testung als Teil meiner Therapieplanung; Candida normal vs. invasiv", orig: "Identifikation der Pilzbelastung", draft: "Die Testung erläutere ich Ihnen als Bestandteil meiner naturheilkundlichen Therapieplanung", withNext: true, why: "Der Testung wird keine bestimmte Nachweisleistung zugeschrieben (dafür gibt es keinen Beleg; CDC äußert sich nicht zu dieser Testung). CDC, Clinical Overview of Invasive Candidiasis (gelesen 07.10.2026) belegt nur die zweite Zeile: Candida ist Kommensale von Darm und Haut; invasive Candidiasis wird über Blutkulturen diagnostiziert." },
  { id: 13, reason: ["Inhalt/Recht"], note: "Grundprinzip: individuelle Reduktion statt vollständiger Verzicht", orig: "Durch vollständigen Verzicht soll das Wachstum gehemmt", draft: "Wie weit Sie Zucker und einfache Kohlenhydrate reduzieren", why: "Für vollständigen Verzicht gibt es keinen klinischen Beleg; passt zu Vorschlag 6/9." },
  { id: 14, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Grundgedanke-Leiste ohne „Kein Zucker = keine Nahrung“", orig: "Kein Zucker = Keine Nahrung für den Pilz", draft: "weniger Zucker – Umfang und Dauer individuell", why: "Wie Vorschlag 13." },
  { id: 15, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Folienüberschrift: „Empfehlenswert vs. eher meiden“", orig: "Übersicht: Erlaubt vs. Verboten", draft: "Übersicht: Empfehlenswert vs. eher meiden", why: "Wie Vorschlag 7: keine pauschalen Verbote." },
  { id: 16, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Folienüberschrift Zucker: „Eher meiden“ statt „Verboten“", orig: "Verboten: Zucker", draft: "Eher meiden: Zucker", why: "Wie Vorschlag 7." },
];
const SIBO: ComparisonChange[] = [
  { id: 1, reason: ["Lesbarkeit"], note: "Einladende Unterzeile statt Pauschal-Disclaimer", orig: "Informationsmaterial - kein Heilversprechen gemaess HWG", draft: "Patienteninformation der Naturheilpraxis Peter Rauch", why: "Der rechtliche Hinweis steht ausführlich am Ende." },
  { id: 2, reason: ["Inhalt/Recht"], note: "Einleitung: individuelle Einordnung statt Ersatz-Satz", orig: "Sie ersetzt keine aerztliche oder heilpraktische Diagnose.", draft: "Die individuelle Einordnung Ihrer Beschwerden erfolgt", why: "Positiv statt pauschal abgrenzend; inhaltlich gleich (Internetseite ≠ Diagnose). Schreibweise ae/oe/ue des Originals beibehalten." },
  { id: 3, reason: ["Inhalt/Recht"], note: "Candida aus dem bakteriellen Gasprofil gelöst", orig: "E. coli, Candida, Enterobacter", draft: "ein Pilz, kein Bakterium", why: "Candida ist ein Pilz; das Wasserstoffprofil beschreibt Bakterien. Die PDF-Nennung bleibt transparent erhalten." },
  { id: 4, reason: ["Inhalt/Recht"], note: "Methan-Profil als IMO (Archaeen) benannt", orig: "heute oft als IMO bezeichnet", draft: "intestinale Methanogen-Ueberwucherung durch Archaeen", why: "ACG-Leitlinie SIBO (Pimentel et al., Am J Gastroenterol 2020;115:165–178), Volltext-PDF am 07.10.2026 abgerufen und gelesen: Methanogene sind Archaeen, keine Bakterien, und können auch im Dickdarm überwuchern; daher „intestinal methanogen overgrowth (IMO)“ statt „methane-SIBO“." },
  { id: 6, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Tabellenzeile: „Methan-Profil (IMO)“ statt „Methan-SIBO“", orig: "Methan-SIBO", draft: "Methan-Profil (IMO)", targetSelector: "strong", why: "Wie Vorschlag 4; ACG-Volltext: IMO passender als „methane-SIBO“." },
  { id: 7, reason: ["Inhalt/Recht"], note: "Hinweistext: Dosierungen nicht mehr „sichtbar“", orig: "bleiben als Originalangaben sichtbar", draft: "Dosierungsangaben des PDF sind nicht Teil dieser Patienteninformation", why: "Nach Vorschlag 5 stehen keine Dosierungen mehr im Text; die Aussage „bleiben sichtbar“ wäre falsch. Originalangaben nur im Quellenprüfartefakt (Repository-Datei, kein Zugriffsschutz-Beleg)." },
  { id: 8, reason: ["Inhalt/Recht"], note: "Quellengrenze: Dosierungen nur in interner Quellenprüfung dokumentiert", orig: "Diese Angaben werden intern erhalten", draft: "Dosierungen sind nur in der internen Quellenpruefung dokumentiert", why: "Wie Vorschlag 7; „intern erhalten“ wird präzisiert, ohne Zugriffsschutz zu behaupten." },
  { id: 5, reason: ["Inhalt/Recht"], note: "Keine öffentlichen Dosen (Allicin 2500 mg u. a.)", orig: "Allicin bis ca. 2500 mg", draft: "Auswahl und Dosierung lege ich individuell", why: "Produkt, Standardisierung und Dosis sind nicht belegt; Extraktmasse ≠ Allicinmenge. Die Originalangaben sind nur im Quellenprüfartefakt dokumentiert (docs/wiki/infothek-quellen-paket2-2026-10-07.json – Repository-Datei, kein Zugriffsschutz-Beleg); die öffentliche Infothek ist dosierungsfrei. Der Entwurf sagt nicht mehr, Dosierungen blieben sichtbar." },
];
const BURN: ComparisonChange[] = [
  { id: 1, reason: ["Lesbarkeit"], note: "Einladende Unterzeile statt Pauschal-Disclaimer", orig: "Informationsmaterial – kein Heilversprechen gemäß HWG", draft: "Patienteninformation der Naturheilpraxis Peter Rauch", why: "Der rechtliche Hinweis steht ausführlich am Ende; auf der Titelfolie wirkt er abschreckend (wie Allergie/Diabetes Vorschlag 1/3)." },
  { id: 2, reason: ["Inhalt/Recht"], note: "Kontakt: Telefonnummer im verbindlichen Format", orig: "0821 2621462 ·", draft: "0821-2621462 ·", why: "Verbindliche Praxisnummer 0821-2621462 (tel:+498212621462 war bereits korrekt). Kontaktkorrektur, keine Inhaltsentscheidung." },
  { id: 3, reason: ["Inhalt/Recht"], note: "Konzept: eigenständige Behandlung statt Ergänzungssatz", orig: "arbeiten bei Erschöpfungsbildern oft", draft: "behandle ich Erschöpfungsbilder", why: "Praxisrollenstandard: eigenständige Behandlung; konkrete Abklärung nur dort, wo medizinisch nötig. Der HWG-Paragraf als Pauschalverweis entfällt, die vorsichtige Formulierung („kann unterstützen“) bleibt." },
  { id: 4, reason: ["Inhalt/Recht"], note: "Warnzeichen: gezielte Untersuchung statt Rücküberweisung", orig: "ggf. Rücküberweisung Arzt", draft: "gezielte ärztliche Untersuchung", why: "Die Sicherheitsprüfung bleibt vollständig; „Rücküberweisung“ suggerierte eine Unterordnung." },
  { id: 5, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Kontaktkasten: Behandlung statt Begleitung", orig: "Individuelle Begleitung bei Erschöpfung", draft: "Individuelle Behandlung bei Erschöpfung", why: "Praxisrollenstandard." },
  { id: 6, reason: ["Inhalt/Recht"], note: "Kontaktkasten ohne pauschalen Abstimmungszusatz", orig: "in Abstimmung mit Ihrer ärztlichen Versorgung", draft: "Vorhandene ärztliche Befunde beziehe ich gerne ein", why: "Wie Kieferostitis Vorschlag 12: kein pauschaler Abstimmungszusatz; vorhandene Befunde optional einbezogen." },
  { id: 7, reason: ["Inhalt/Recht"], note: "Ashwagandha: individuelle Auswahl + BfR-Sicherheitshinweis", orig: "kann Cortisol-Regulation unterstützen", draft: "pflanzliches Adaptogen, Auswahl nach individueller Prüfung", why: "Die Cortisol-Aussage war nur mit einer PubMed-Suchabfrage begründet. BfR-Mitteilung 39/2024 (gelesen): insbesondere Kinder, Schwangere, Stillende und Menschen mit aktuellen/früheren Lebererkrankungen sollen Ashwagandha nicht einnehmen; Fallberichte zu Leberschäden." },
  { id: 8, reason: ["Inhalt/Recht"], note: "Bewegung an Belastbarkeit anpassen (PEM)", orig: "Ideal bei Energiemangel", draft: "Intensität an Ihre Belastbarkeit anpassen", why: "Widersprach dem PEM-Hinweis des Artikels. NICE NG206, Empfehlungen 1.11.9–1.11.14 (gelesen): keine generalisierten oder fest gesteigerten Programme; Ausgangsniveau so, dass Symptome nicht zunehmen." },
  { id: 9, reason: ["Inhalt/Recht"], note: "Adaptogene: Suchlinks durch Sicherheitshinweis ersetzt", orig: "zeigen in klinischen Studien (randomisiert, placebokontrolliert)", draft: "wähle ich individuell aus", why: "Die Wirksamkeitsaussage war nur mit Suchabfragen statt konkreten Studien belegt; ersetzt durch individuelle Auswahl + BfR-Hinweis. Akupunktur-Satz und -Link unverändert (eigener Prüfpunkt)." },
];
const KRAEU: ComparisonChange[] = [
  { id: 1, reason: ["Lesbarkeit"], note: "Einladende Unterzeile statt Pauschal-Disclaimer", orig: "Informationsmaterial – kein Heilversprechen gemäß HWG", draft: "Patienteninformation der Naturheilpraxis Peter Rauch", why: "Der rechtliche Hinweis steht ausführlich am Ende; auf der Titelfolie wirkt er abschreckend (wie Allergie/Diabetes Vorschlag 1/3)." },
  { id: 2, reason: ["SEO", "Inhalt/Recht"], note: "Meta-Beschreibung: Tippfehler und „bei“ statt „gegen“", headOnly: { kind: "description", before: "Klassische Kräuter und Küchengwürze gegen Schmerz und Entzündung", after: "Klassische Kräuter und Küchengewürze bei Schmerz und Entzündung" }, why: "Tippfehler „Küchengwürze“ korrigiert; „bei“ ist sprachlich zurückhaltender als „gegen“, schließt aber ein Wirkversprechen nicht pauschal aus – Wirkungs- und Sicherheitsangaben werden separat geprüft." },
  { id: 3, reason: ["Inhalt/Recht"], note: "Metatron-Hospital in meiner Therapieplanung", orig: "Identifikation und Behandlung von Schmerzursachen", draft: "die Hinweise aus der Analyse beziehe ich", why: "Metatron-Hospital bleibt ein zentraler Baustein von Peters Therapieplanung; die Analyse liefert Hinweise für die Behandlung, keinen schulmedizinischen Diagnosenachweis. „Identifikation von Schmerzursachen“ behauptete einen Diagnosenachweis." },
  { id: 4, reason: ["Inhalt/Recht"], note: "Pflanzliche Mittel als Baustein der Behandlung", orig: "sie ersetzen keine ärztliche Behandlung", draft: "Ihre laufenden Medikamente beziehe ich in die Planung ein", why: "Praxisrollenstandard ohne pauschale Unterordnung. Der konkrete Hinweis „Kein Ersatz für ärztliche Schmerztherapie bei akuten oder schweren Schmerzzuständen“ bleibt als fallbezogene Sicherheitsaussage unverändert." },
  { id: 5, reason: ["Inhalt/Recht"], note: "Weidenrinde: keine Magen-Überlegenheit, Gegenanzeigen", orig: "magenverträglicher als synthetisches ASS", draft: "Salicin wird im Körper zu Salicylsäure umgewandelt", why: "EMA, Salicis cortex (gelesen): Salicin → Salicylsäure; Magen-Darm-Beschwerden möglich; nicht bei Überempfindlichkeit gegen Salicylate oder andere NSAR, einschließlich dadurch ausgelösten Asthmas. Eine Magenverträglichkeits-Überlegenheit ist dort nicht belegt." },
  { id: 6, reason: ["Inhalt/Recht"], note: "Capsaicin-Pflaster: keine Selbstanleitung", orig: "Bei chronischen Nervenschmerzen", draft: "Präparat und Anwendung legen wir fachlich fest", why: "EMA EPAR Qutenza (8 %, gelesen): Anwendung durch Arzt bzw. Fachpersonal unter ärztlicher Aufsicht." },
];

const DANK: ComparisonChange[] = [
  { id: 1, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Schlusshinweis: Einladung statt pauschaler Ersatz-Formel", orig: "Sie ersetzt keine Diagnose, Psychotherapie", draft: "besprechen wir das gerne in meiner Praxis", why: "Praxisrollenstandard: keine pauschale Negativformel; „kein Heilversprechen“ bleibt. Der konkrete Sicherheitskasten (professionelle Hilfe, 112 bei akuter Gefahr) bleibt unverändert. Studieninhalt (JAMA Psychiatry 2024, 49.275 Frauen, ca. 9 % niedrigeres Sterberisiko, Zusammenhang statt Ursache) laut Astra-Prüfung stimmig, daher unverändert." },
];
const UMWELT: ComparisonChange[] = [
  { id: 1, reason: ["Lesbarkeit"], note: "Einladende Unterzeile statt Pauschal-Disclaimer", orig: "Informationsmaterial – kein Heilversprechen gemäß HWG", draft: "Patienteninformation der Naturheilpraxis Peter Rauch", why: "Rechtlicher Hinweis steht ausführlich am Ende (wie andere Artikel Vorschlag 1)." },
  { id: 2, reason: ["Inhalt/Recht"], note: "PTFE-Pfannen: BfR-Einordnung, Überhitzen ≠ Kratzer", orig: "können bei Überhitzung oder Beschädigung Stoffe abgeben", draft: "bei bestimmungsgemäßem Gebrauch keine gesundheitlichen Beeinträchtigungen", why: "BfR-FAQ PTFE-Geschirr vom 02.07.2025 (gelesen): Risiko nur, wenn ungefüllt stark erhitzt; ab 360 °C gesundheitsschädliche Dämpfe; bei bestimmungsgemäßem Gebrauch keine gesundheitlichen Beeinträchtigungen zu erwarten. Alternative Pfannen bleiben genannt." },
  { id: 3, reason: ["Inhalt/Recht"], note: "Bienenwachstücher: nicht für rohes Fleisch/Fisch", orig: "Glasdosen", draft: "nicht für rohes Fleisch oder rohen Fisch", why: "Verbraucherzentrale NRW (Stand 25.08.2026, gelesen): nicht heiß spülbar (Wachs schmilzt ca. 62 °C), daher hygienisch nicht für rohes Fleisch und Fisch. BfR-FAQ 11.09.2023: Übergang von Wachsbestandteilen in fettige Lebensmittel möglich; die Roh-Lebensmittel-Aussage selbst stammt aus der VZ-Quelle." },
  { id: 4, reason: ["Inhalt/Recht"], note: "Raumduft: ätherische Öle sind Duftstoffe", orig: "naturreine ätherische Öle sparsam einsetzen", draft: "auch ätherische Öle sind Duftstoffe", why: "UBA-Ratgeber Duftstoffe (gelesen): natürliche Duftstoffe sind im Allgemeinen nicht weniger belästigend oder allergieauslösend als synthetische; Geruch oft Warnsignal, dass gelüftet werden sollte." },
  { id: 5, reason: ["Inhalt/Recht"], note: "Naturkosmetik nicht automatisch duftstoffarm", orig: "Naturkosmetik mit anerkannten Siegeln", draft: "Naturkosmetik ist nicht automatisch duftstoffarm", why: "Wie Vorschlag 4; UBA empfiehlt bei Empfindlichkeit Produkte mit Hinweis „Ohne Duftstoffe“." },
  { id: 6, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Drei Stufen: verständliche Einordnung statt Rechtsbehauptung", orig: "So bleibt jede Aussage fachlich korrekt und juristisch zurückhaltend", draft: "So können Sie jede Aussage verständlich einordnen", why: "Eine Wortwahl garantiert keine fachliche oder juristische Richtigkeit; beschrieben wird der Nutzen der Unterscheidung." },
  { id: 7, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Überschrift: Behandlung statt Begleitung", orig: "Beratung & Begleitung", draft: "Beratung & Behandlung in meiner Praxis", why: "Praxisrollenstandard." },
  { id: 8, reason: ["Inhalt/Recht"], note: "Kontakttext: eigenständige Praxisarbeit", orig: "Ich begleite Sie gerne bei einer ganzheitlichen Betrachtung", draft: "In meiner Praxis betrachten wir gemeinsam ganzheitlich", why: "Praxisrollenstandard; kein Wirkversprechen." },
  { id: 9, reason: ["Inhalt/Recht"], note: "Telefonnummer im verbindlichen Format", orig: "0821 2621462 ·", draft: "0821-2621462 ·", why: "Verbindliche Praxisnummer; tel:+498212621462 und praxis_rauch@icloud.com waren bereits korrekt." },
];

const LOGI: ComparisonChange[] = [
  { id: 1, reason: ["Inhalt/Recht", "Lesbarkeit"], note: "Kontaktkasten: gemeinsame Planung statt Begleitung", orig: "Ich begleite Sie gerne bei der Umstellung", draft: "In meiner Praxis planen wir gemeinsam Ihre Umstellung", why: "Praxisrollenstandard; kein Wirkversprechen. Rechtlicher Abschluss unverändert." },
];
const MITO: ComparisonChange[] = [
  { id: 1, reason: ["Inhalt/Recht"], note: "Einleitungshinweis: Einordnung in meiner Praxis statt Ersatz-Satz", orig: "Es ersetzt keine ärztliche Diagnose, sondern dient der Information.", draft: "die individuelle Einordnung Ihrer Beschwerden nehmen wir in meiner Praxis vor", why: "Praxisrollenstandard. Die Kennzeichnung als kontrovers diskutiertes Erklärungsmodell und die konkreten Warnhinweise (Differentialdiagnose, Bildgebung vor HWS-Behandlung, akute neurologische Symptome) bleiben unverändert." },
  { id: 2, reason: ["Inhalt/Recht"], note: "Fußzeile ohne pauschale Unterordnung", orig: "keine Ersatzleistung zur ärztlichen Versorgung", draft: "Heilpraktiker Peter Rauch · Augsburg · keine Heilversprechen.", why: "Pauschaler Negativzusatz entfällt; „keine Heilversprechen“ bleibt." },
];
const PARAS: ComparisonChange[] = [
  { id: 1, reason: ["Lesbarkeit"], note: "Einladende Unterzeile statt Pauschal-Disclaimer", orig: "Informationsmaterial – kein Heilversprechen gemäß HWG", draft: "Patienteninformation der Naturheilpraxis Peter Rauch", why: "Rechtlicher Hinweis steht ausführlich am Ende." },
  { id: 2, reason: ["Inhalt/Recht"], note: "Trikombin: „Testung“ statt „Diagnostik“", orig: "Diagnostik & Therapie:", draft: "Testung & Therapie:", why: "Keine Diagnoseleistung behauptet; Verfahren bleibt als Testung und Therapie beschrieben." },
  { id: 3, reason: ["Inhalt/Recht"], note: "Metatron: zentraler Baustein, kein Erregernachweis", orig: "Frequenzbasierte Untersuchung von Organsystemen", draft: "Ein zentraler Baustein meiner Therapieplanung", why: "Metatron-Hospital ist zentraler Baustein von Peters Therapieplanung; ein Erregernachweis wird nicht zugeschrieben." },
  { id: 4, reason: ["Inhalt/Recht"], note: "Praxisabsatz: Einsatz als Teil meiner Therapieplanung", orig: "nicht dem Ersatz einer schulmedizinischen Diagnostik und Therapie", draft: "als Teil meiner Therapieplanung", why: "Praxisrollenstandard ohne pauschale Unterordnung; Einordnung als Erfahrungsheilkunde bleibt im selben Absatz." },
  { id: 5, reason: ["Inhalt/Recht"], note: "Sprechzeit: belegte Zahl mit Jahr statt Pauschalurteil", orig: "7-8 Minuten pro Patient in der Kassenpraxis", draft: "Eine ältere Erhebung (Daten von 2002)", why: "Irving G et al., BMJ Open 2017;7:e017902 (Volltext via Europe PMC PMC5695512, gelesen 07.10.2026): Tabelle Deutschland „2002 Video … 7.6“ Minuten, 889 Konsultationen. Grenze: Daten von 2002; die Folgerung, Differentialdiagnostik „unterbleibe“, ist dort nicht belegt und entfällt." },
];
const VIREN: ComparisonChange[] = [
  { id: 1, reason: ["Inhalt/Recht"], note: "Komplementäre Verfahren: Hinweise für Therapieplanung, kein Laborbefund", orig: "Komplementäre Diagnostik kann Hinweise liefern", draft: "Komplementäre Verfahren wie die Metatron-Analyse liefern Hinweise", why: "Die Behauptung, Routinediagnostik erfasse etwas nicht, was diese Verfahren erfassen, ist nicht belegt; Metatron bleibt zentraler Baustein der Therapieplanung." },
  { id: 2, reason: ["Inhalt/Recht"], note: "Sprechzeit: belegte Zahl mit Jahr", orig: "4. Zeitdruck in der Sprechstunde:", draft: "4. Kurze Sprechzeiten:", why: "Irving G et al., BMJ Open 2017;7:e017902 (Volltext via Europe PMC PMC5695512, gelesen 07.10.2026): Tabelle Deutschland „2002 Video … 7.6“ Minuten, 889 Konsultationen. Grenze: Daten von 2002; die Folgerung, Differentialdiagnostik „unterbleibe“, ist dort nicht belegt und entfällt." },
  { id: 3, reason: ["Inhalt/Recht"], note: "Metatron-Kasten: zentraler Baustein, kein Erregernachweis", orig: "Erfassung von Frequenzmustern", draft: "zentraler Baustein meiner Therapieplanung", why: "Metatron-Hospital ist zentraler Baustein von Peters Therapieplanung; ein labordiagnostischer Erregernachweis wird nicht zugeschrieben." },
];

const topicsOf = (c: ComparisonChange[]) => Object.fromEntries(c.map((x) => [x.id, x.note]));

const VIEVA: ComparisonChange[] = [
  {"id": 1, "reason": ["Inhalt/Recht"], "note": "Kurzbeschriftung: LF ist kein eindeutiger Stressmarker.", "orig": "LF (Sympathikus/Langfrist. Stress)", "draft": "LF (niederfrequenter Anteil)", "why": "Kurzbeschriftung: LF ist kein eindeutiger Stressmarker. Quelle: https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1469-8986.1994.tb02351.x"},
  {"id": 2, "reason": ["Inhalt/Recht"], "note": "Kurzbeschriftung: Verhältnis nur im Kontext deutbar.", "orig": "LF/HF (Balance VNS)", "draft": "LF/HF (Verhältnis)", "why": "Kurzbeschriftung: Verhältnis nur im Kontext deutbar. Quelle: https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1469-8986.1994.tb02351.x"},
  {"id": 3, "reason": ["Inhalt/Recht"], "note": "Experimentelle Primärstudie (Abstract gelesen, nicht Volltext; keine V", "orig": "Kennzeichen für inneren Druck. Gibt einen Hinweis auf das sympathische Nervensystem, barorezeptorische Aktivität und langfristigen Stress.", "draft": "Niederfrequenter Anteil der Herzratenvariabilität. Er wird von sympathischen, parasympathischen und barorezeptorischen Einflüssen mitgeprägt; ich deute ihn zusammen mit Messbedingungen und Ihren Beschwerden, nicht als eigenständige Stressdiagnose.", "why": "Experimentelle Primärstudie (Abstract gelesen, nicht Volltext; keine Vieva-Validierung): LF nicht rein sympathisch. Quelle: https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1469-8986.1994.tb02351.x"},
  {"id": 4, "reason": ["Inhalt/Recht"], "note": "Wie Ä3; Abstract, keine Vieva-Validierung.", "orig": "Das Verhältnis von LF zu HF ist ein Ausdruck für die Balance des vegetativen Nervensystems zwischen Sympathikus (Anspannung) und Parasympathikus (Entspannung).", "draft": "Das Verhältnis von LF zu HF beschreibt die Anteile beider Frequenzbereiche. Zusammen mit Messbedingungen und Ihren Beschwerden gibt es mir Hinweise für die Therapieplanung; ein einzelner Wert ist keine eindeutige Aussage über die vegetative Balance.", "why": "Wie Ä3; Abstract, keine Vieva-Validierung. Quelle: https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1469-8986.1994.tb02351.x"},
  {"id": 5, "reason": ["Inhalt/Recht"], "note": "Keine gemessene Knochendichte vortäuschen; Vorbefunde individuell berü", "orig": "Grad der Osteoporose", "draft": "Software-Rubrik „Osteoporose“", "why": "Keine gemessene Knochendichte vortäuschen; Vorbefunde individuell berücksichtigen. Vieva-Validierung offen. Quelle: https://gesund.bund.de/osteoporose"},
  {"id": 6, "reason": ["Inhalt/Recht"], "note": "Wie Ä5.", "orig": "Knochendichte", "draft": "Software-Rubrik „Knochendichte“ (keine Messung)", "why": "Wie Ä5. Quelle: https://gesund.bund.de/osteoporose"},
];
const ZAPPER: ComparisonChange[] = [
  {"id": 1, "reason": ["Inhalt/Recht"], "note": "Anleitung gelesen (Professional, S. 7): Anwendung bei Herzschrittmache", "orig": "Besondere Vorsicht bei Herzschrittmachern oder anderen implantierten elektronischen Geräten.", "draft": "Bei Herzschrittmachern oder anderen implantierten elektronischen Geräten keine Anwendung: Die Bedienungsanleitung des Modells Diamond Shield Professional (S. 7) untersagt dies ausdrücklich; für andere Modelle gilt die jeweilige Anleitung.", "why": "Anleitung gelesen (Professional, S. 7): Anwendung bei Herzschrittmacher untersagt. Gilt nur für dieses Modell belegt; Peters eigenes Modell nicht behauptet. Quelle: https://alternativgesund.de/media/pdf/68/38/04/Bedienungsanleitung-Diamond-Shield-Professional-deutsch-englisch.pdf"},
];
export const COMPARISON_CONFIGS: ComparisonConfig[] = [
  { slug: "krankheit-ist-messbar", heading: "Frequenztherapie („Krankheit ist messbar“)", base: { kind: "delivered", route: "/krankheit-ist-messbar.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: kimDraft, changes: KRANKHEIT_IST_MESSBAR_CHANGES, topics: KIM_TOPICS, notes: KIM_NOTES, extraChecks: EXTRA_CHECKS, reportTitle: "Krankheit ist messbar (Frequenztherapie)", naming: true },
  { slug: "allergiebehandlung", heading: "Allergiebehandlung", base: { kind: "delivered", route: "/allergiebehandlung.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: allergieDraft, changes: ALLERGIE, topics: topicsOf(ALLERGIE), notes: ["Kontaktkorrektur (von Peter autorisiert, 07.10.2026, keine Inhaltsentscheidung): Telefon 0821-2621462 / tel:+498212621462 statt 0821 2177 2670 / tel:+49821217726700 – im Entwurf und in der Arbeitsfassung angewandt; Original links unverändert als Ausgangsstand.", "Geschützte Patientenfolien (TCM, Orthomolekular, Psychosomatik) bleiben unverändert und wurden nicht bearbeitet."], extraChecks: ["20–30 %-Angabe: Primärquelle von Peter offen (Vorschlag 4).", "Öffentliche Seite: Seitentitel/Meta im ausgelieferten Seitenkopf, Prüfdatum, Veröffentlichung separat."], reportTitle: "Allergiebehandlung" },
  { slug: "kieferostitis", heading: "Kieferostitis (neuer Artikel)", base: { kind: "baseDraft", html: kieferBase }, leftLabel: "Basisentwurf (Arbeitsstand – nie veröffentlicht)", draftHtml: kieferDraft, changes: KIEFER, topics: topicsOf(KIEFER), notes: ["Kontaktkorrektur (von Peter autorisiert, 07.10.2026, keine Inhaltsentscheidung): Telefon 0821-2621462 / tel:+498212621462 statt 0821 2177 2670 / tel:+49821217726700 – im Entwurf und in der Arbeitsfassung angewandt; Basisentwurf ebenfalls korrigiert.", "Neuer Artikel: Es gibt keine bisher veröffentlichte Fassung. Links steht der erste Arbeitsstand, rechts der überarbeitete Entwurf.", "Freigabe von Textänderungen und Veröffentlichung sind getrennte Schritte; der Entwurf ist noindex und nicht verlinkt."], extraChecks: ["Enteroviren: Ergebnis als offene Forschungsfrage (Vorschlag 8); keine klinische Humanstudie gefunden.", "Handyansicht noch ansehen.", "Neuer Artikel: noindex bis Freigabe, Veröffentlichung separat."], reportTitle: "Kieferostitis (neuer Artikel)" },
  { slug: "ass-salicylat-histamin", heading: "ASS-Intoleranz, Salicylat & Histamin", base: { kind: "delivered", route: "/ass-salicylat-histamin.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: assDraft, changes: ASS, topics: topicsOf(ASS), notes: ["Telefon 0821-2621462 und E-Mail praxis_rauch@icloud.com im Entwurf bereits korrekt; Kontaktkorrektur gilt auch für die Arbeitsfassung."], extraChecks: ["Prävalenz 0,6–2,5 % (Allgemeinbevölkerung) und 10–20 % (Asthma): Primärquelle im Artikel ergänzen (z. B. Kowalski et al., Allergy 2019 EAACI/GA²LEN; Jenkins et al., BMJ 2004) – noch nicht am Volltext verifiziert.", "Salicylat-/Histamin-Mengenangaben (Schälen −50 %, Frisch −90 %, Biere <0,05 mg/l): Primärquellen offen.", "Markennamen (Biere) – Nennung prüfen.", "Pils: Detailtabelle Histamin grün, Übersicht „mittel“ – Einstufung offen für Peter.", "Veröffentlichung separat."], reportTitle: "ASS-Intoleranz, Salicylat & Histamin" },
  { slug: "diabetes-handout", heading: "Diabetes Typ 1 & Typ 2 – Handout", base: { kind: "delivered", route: "/diabetes-handout.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: diabDraft, changes: DIAB, topics: topicsOf(DIAB), notes: ["Telefon 0821-2621462 und E-Mail praxis_rauch@icloud.com im Entwurf bereits korrekt; Kontaktkorrektur gilt auch für die Arbeitsfassung."], extraChecks: ["DDG-Zielwerte (HbA1c < 7,0 %, postprandial 140–180 mg/dl) gegen aktuelle Nationale VersorgungsLeitlinie/DDG-Praxisempfehlung abgleichen.", "Orthomolekulare Angaben: Einzelstudien im Artikel nicht genannt – Quellen offen.", "Veröffentlichung separat."], reportTitle: "Diabetes-Handout" },
  { slug: "ersttermin-naturheilpraxis", heading: "Ihr erster Termin", base: { kind: "delivered", route: "/ersttermin-naturheilpraxis.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: ersttDraft, changes: ERSTT, topics: topicsOf(ERSTT), notes: ["Telefon 0821-2621462 und E-Mail praxis_rauch@icloud.com im Entwurf bereits korrekt; Kontaktkorrektur gilt auch für die Arbeitsfassung."], extraChecks: ["Frage an Peter: Ersttermin nennt keinen festen Zeitrahmen, Therapieweg schreibt „Ersttermin – nur Diagnostik (ca. 3 Stunden)“ und zugleich Trikombin/Vieva „sofern Zeit, sonst Folgetermin“. Kein Widerspruch im Wortlaut, aber Ablauf bitte vereinheitlichen.", "Stand-Datum (6. August 2026) nach Freigabe aktualisieren.", "Veröffentlichung separat."], reportTitle: "Ihr erster Termin" },
  { slug: "therapieweg-uebersicht", heading: "Ihr Therapieweg – Übersicht", base: { kind: "delivered", route: "/therapieweg-uebersicht.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: twDraft, changes: TW, topics: topicsOf(TW), notes: ["Telefon 0821-2621462 und E-Mail praxis_rauch@icloud.com im Entwurf bereits korrekt; Kontaktkorrektur gilt auch für die Arbeitsfassung."], extraChecks: ["Weitere „Begleitung“-Stellen (Trikombin & Begleitung, Begleitende Therapie, Ernährung & Begleitung) bewusst unverändert: dort beschreibt es Folgemaßnahmen, keine Unterordnung – bei Bedarf eigener Vorschlag.", "Veröffentlichung separat."], reportTitle: "Ihr Therapieweg" },
  { slug: "candida-diaet", heading: "Candida-Diät", base: { kind: "delivered", route: "/candida-diaet.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: candidaDraft, changes: CAND, topics: topicsOf(CAND), notes: ["Telefon 0821-2621462 und E-Mail praxis_rauch@icloud.com geprüft."], extraChecks: ["Ernährungsangaben (erlaubt/verboten, Dauer) ohne Primärquellen im Artikel – Prüfpunkt, keine Änderung.", "Haftungsausschluss am Ende bewusst unverändert.", "Veröffentlichung separat."], reportTitle: "Candida-Diät" },
  { slug: "sibo-duenndarmfehlbesiedlung", heading: "SIBO – Dünndarmfehlbesiedlung", base: { kind: "delivered", route: "/sibo-duenndarmfehlbesiedlung.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: siboDraft, changes: SIBO, topics: topicsOf(SIBO), notes: ["Seite enthält keinen Praxis-Kontaktkasten (kein Telefon/E-Mail) – Ergänzung wäre eigener Vorschlag."], extraChecks: ["Namensnennung Dr. med. Ralf Kirkamm und Quelle „bereitgestelltes PDF“: mit Anonymisierungs-/Urheberrichtlinie abgleichen (Peter).", "Durchgehend ae/oe/ue statt Umlauten – eigener Vorschlag möglich.", "Veröffentlichung separat."], reportTitle: "SIBO" },
  { slug: "muedigkeit-erschoepfung-burnout", heading: "Müdigkeit, Erschöpfung & Burnout", base: { kind: "delivered", route: "/muedigkeit-erschoepfung-burnout.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: burnoutDraft, changes: BURN, topics: topicsOf(BURN), notes: ["Telefon 0821-2621462 und E-Mail praxis_rauch@icloud.com geprüft."], extraChecks: ["Prävalenz- und Kassenreportzahlen (RKI, TK, Eurofound, OECD) nicht neu am Original geprüft – Prüfpunkt.", "Veröffentlichung separat."], reportTitle: "Müdigkeit, Erschöpfung & Burnout" },
  { slug: "kraeuter-schmerz-entzuendung", heading: "Kräuter bei Schmerz & Entzündung", base: { kind: "delivered", route: "/kraeuter-schmerz-entzuendung.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: kraeuterDraft, changes: KRAEU, topics: topicsOf(KRAEU), notes: ["Telefon 0821-2621462 und E-Mail praxis_rauch@icloud.com geprüft."], extraChecks: ["Wirkungs-/Nebenwirkungsangaben je Kraut ohne neu gelesene Primärquellen – Prüfpunkt, keine Änderung.", "Veröffentlichung separat."], reportTitle: "Kräuter bei Schmerz & Entzündung" },
  { slug: "dankbarkeit-alltag", heading: "Dankbarkeit im Alltag", base: { kind: "delivered", route: "/dankbarkeit-alltag.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: dankDraft, changes: DANK, topics: topicsOf(DANK), notes: ["Inhalt laut Astra sachlich stimmig – bewusst nur ein Vorschlag."], extraChecks: ["JAMA-Volltext (403) nicht selbst abgerufen; Zahlen laut Astra-Prüfung.", "Veröffentlichung separat."], reportTitle: "Dankbarkeit im Alltag" },
  { slug: "umwelt-alltag-gesundheit", heading: "Umwelt, Alltag & Gesundheit", base: { kind: "delivered", route: "/umwelt-alltag-gesundheit.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: umweltDraft, changes: UMWELT, topics: topicsOf(UMWELT), notes: ["Telefon 0821-2621462 und E-Mail praxis_rauch@icloud.com geprüft."], extraChecks: ["Haftungsausschluss am Ende bewusst unverändert.", "Übrige Tabellenzeilen ohne neue Primärquellenprüfung.", "Veröffentlichung separat."], reportTitle: "Umwelt, Alltag & Gesundheit" },
  { slug: "logi-ernaehrung-mitochondrien", heading: "LOGI-Kost & Mitochondrien-Ernährung", base: { kind: "delivered", route: "/logi-ernaehrung-mitochondrien.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: logiDraft, changes: LOGI, topics: topicsOf(LOGI), notes: ["Kontaktdaten 0821-2621462 / praxis_rauch@icloud.com unverändert geprüft."], extraChecks: ["Ernährungs- und Buchangaben (Kuklinski) nicht an Primärstudien geprüft – Prüfpunkt.", "Veröffentlichung separat."], reportTitle: "LOGI-Kost & Mitochondrien-Ernährung" },
  { slug: "mitochondropathie-hws", heading: "Mitochondropathie & instabile HWS", base: { kind: "delivered", route: "/mitochondropathie-hws.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: mitoDraft, changes: MITO, topics: topicsOf(MITO), notes: ["Kontaktdaten 0821-2621462 / praxis_rauch@icloud.com unverändert geprüft."], extraChecks: ["Labor-/Markerangaben (Citrullin, ATP-Test) nicht an Primärquellen geprüft – Prüfpunkt.", "Veröffentlichung separat."], reportTitle: "Mitochondropathie & instabile HWS" },
  { slug: "parasiten-deutschland", heading: "Parasiten in Deutschland", base: { kind: "delivered", route: "/parasiten-deutschland.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: parasDraft, changes: PARAS, topics: topicsOf(PARAS), notes: ["Kontaktdaten 0821-2621462 / praxis_rauch@icloud.com unverändert geprüft."], extraChecks: ["Prävalenz-/Sensitivitätszahlen (Toxoplasma 50 %, Toxocara 2–37 %, Stuhl 50 % vs. 60–70 %) und KV-Laborbudget-Aussage nicht neu geprüft – Prüfpunkt.", "Veröffentlichung separat."], reportTitle: "Parasiten in Deutschland" },
  { slug: "viren-bakterien-deutschland", heading: "Viren & Bakterien in Deutschland", base: { kind: "delivered", route: "/viren-bakterien-deutschland.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: virenDraft, changes: VIREN, topics: topicsOf(VIREN), notes: ["Kontaktdaten 0821-2621462 / praxis_rauch@icloud.com unverändert geprüft."], extraChecks: ["Tabellen (50 Bakterien/50 Viren) nicht einzeln an Primärquellen geprüft – Prüfpunkt.", "DEGAM-/SGB-V-/Weiterbildungsaussagen nicht neu gelesen.", "Veröffentlichung separat."], reportTitle: "Viren & Bakterien in Deutschland" },
  { slug: "vieva-pro-vitalanalyse", heading: "Vieva Pro Vitalanalyse", base: { kind: "delivered", route: "/vieva-pro-vitalanalyse.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: vievaDraft, changes: VIEVA, topics: topicsOf(VIEVA), notes: ["13 Folien (div.slide, tatsächlich gezählt) im Vergleich nacheinander sichtbar.", "Kontaktdaten 0821-2621462 / praxis_rauch@icloud.com geprüft."], extraChecks: ["HRV-Beleg nur Abstract gelesen, keine Vieva-Validierung – Prüfpunkt.", "Veröffentlichung separat."], reportTitle: "Vieva Pro Vitalanalyse" },
  { slug: "zapper-diamond-shield", heading: "Zapper – Diamond Shield", base: { kind: "delivered", route: "/zapper-diamond-shield.html" }, leftLabel: "Original (aktuell ausgeliefert)", draftHtml: zapperDraft, changes: ZAPPER, topics: topicsOf(ZAPPER), notes: ["Herzschrittmacher-Verbot nur für Modell Professional per Anleitung belegt; Peters Modell nicht behauptet."], extraChecks: ["Weitere Wirk-/Erreger-/Physikaussagen nicht an Primärquellen geprüft – Prüfpunkt.", "Veröffentlichung separat."], reportTitle: "Zapper – Diamond Shield" },
];
export const configFor = (slug: string | undefined) => COMPARISON_CONFIGS.find((c) => c.slug === slug) ?? COMPARISON_CONFIGS[0];
