INSERT INTO public.admin_knowledge_base (title, category, tags, content) VALUES
(
  'Vitaplace Infusion Anti-Stress – Therapieprotokoll',
  'Naturheilpraxis Peter Rauch > Vitaplace > Therapieprotokolle',
  ARRAY['vitaplace','infusion','anti-stress','stress','burnout','panikattacken','schlaf','beruhigung','calmvalera','magnesium','b-vitamine','pascorbin','therapieprotokoll'],
  E'## Therapieprotokoll Anti-Stress\n\n**Name der Infusion:** Vitaplace Infusion Anti-Stress\n\n### 1. Infusion\n- 1 Amp. Calmvalera Inj. Hevert\n- 1 Amp. Folsäure Hevert 5 mg\n- 1 Amp. Vit. B1 Hevert 200 mg\n- 1 Amp. Vit. B6 Hevert 50 mg\n- 1 Amp. Vit. B12 Depot Hevert\n- 1 Amp. Dystologes Loges\n- 1 Amp. Magnesiocard Verla 72,9 mg Mg\n- 2 Amp. Pascorbin 750 mg/5 ml\n- 250 ml NaCl 0,9 %\n\n**Frequenz:** 2–3× / Woche je nach Bedarf über 3–5 Wochen\n**Dauer der Infusion:** 45 min\n**Hinweis:** langsam infundieren wegen Kreislaufstabilität / Magnesiumflash\n\n### 2. Orale Medikation\n- **Vitaplace Komplex RELaku:** 3–5× 10 Tro. tgl. (Panikattacken)\n- **Vitaplace Komplex GNt:** 3–5× 20 Glo. tgl. (Beruhigung leicht)\n- **Vitaplace Komplex GSn:** 2× 20 Glo. mittags + abends (Schlaf)\n- **Vitaplace Stress Balance Kps:** 2× 1 Kps. tgl. tagsüber (Beruhigung basic)'
),
(
  'Vitaplace Infusion Allergie – Therapieprotokoll',
  'Naturheilpraxis Peter Rauch > Vitaplace > Therapieprotokolle',
  ARRAY['vitaplace','infusion','allergie','heuschnupfen','histamin','nahrungsmittelunverträglichkeit','insektenstiche','pascorbin','engystol','therapieprotokoll'],
  E'## Therapieprotokoll Allergie\n\n**Name der Infusion:** Vitaplace Infusion Allergie\n\n### 1. Infusion\n- 1 Amp. Allergie Injektopas Pascoe\n- 1 Amp. Engystol Heel\n- 1 Amp. Histamin Inj. Heel\n- 4 Amp. Pascorbin 750 mg/5 ml\n- 100 ml NaCl 0,9 %\n\n**Frequenz:**\n- Akut: 2–3× / Woche\n- Präventiv: 1–2× / Woche über 5 Wochen\n\n**Dauer der Infusion:** 30 min\n\n### 2. Orale Medikation\n**Heuschnupfen — Vitaplace Komplex HSnu:**\n- Akut: 5× 10 Globuli tgl. (Kinder ½)\n- Präventiv: 3× 10 Globuli tgl. (Kinder ½)\n\n**Haut, Nahrungsmittelunverträglichkeiten, Insektenstiche — Vitaplace Komplex IAku:**\n- Akut: 10 Globuli alle 15 Minuten\n- Präventiv: 3× 10 Globuli tgl.\n\n**Langfristig:** Vitaplace Komplex DHISTA'
),
(
  'Vitaplace Infusion Asthma/COPD – Therapieprotokoll',
  'Naturheilpraxis Peter Rauch > Vitaplace > Therapieprotokolle',
  ARRAY['vitaplace','infusion','asthma','copd','bronchien','atemwege','engystol','spascupreel','artemisia','baikal-helmkraut','pascorbin','therapieprotokoll'],
  E'## Therapieprotokoll Asthma / COPD\n\n**Name der Infusion:** Vitaplace Infusion Asthma/COPD\n\n### 1. Infusion\n- 1 Amp. Engystol Heel\n- 1 Amp. Spascupreel Heel\n- 1 Amp. Asthma Injektopas Pascoe\n- 1 Amp. Broncho Injektopas Pascoe\n- 1 Amp. Metasolidago S Fackler\n- 1 Amp. Metavirulent Fackler\n- 6 Amp. Pascorbin 750 mg/5 ml\n- 250 ml NaCl 0,9 %\n\n**Frequenz:** 2× / Woche für 5 Wochen\n**Dauer der Infusion:** 45 min\n\n### 2. Orale Medikation\n- **Vitaplace Basis EK-Mischung:** 3–5× 20 Tro. tgl. (Bronchien)\n- **Vitaplace Artemisia Annua UT + Baikal Helmkraut UT (Rx!):** 3–5× 20 Tro. tgl. (Breitbandtherapie)\n- **Vitaplace Husten-Saft** bei Schleimbildung zum Abhusten: alle 2 Std. 2 Teelöffel — Flasche muss in 3 Tagen leer sein!'
),
(
  'Vitaplace Infusion Immun-Boost – Therapieprotokoll',
  'Naturheilpraxis Peter Rauch > Vitaplace > Therapieprotokolle',
  ARRAY['vitaplace','infusion','immunsystem','immun-boost','abwehr','vitamin-d','q10','nadh','magnesium','b-vitamine','pascorbin','engystol','therapieprotokoll'],
  E'## Therapieprotokoll Immun-Boost\n\n**Name der Infusion:** Vitaplace Infusion Immun-Boost\n\n### 1. Infusion\n- 1 Amp. Folsäure Hevert 5 mg\n- 1 Amp. Engystol Heel\n- 1 Amp. Vit. B1 Hevert 200 mg\n- 1 Amp. Vit. B6 Hevert 50 mg\n- 1 Amp. Solidago comp. Heel\n- 1 Amp. Vit. B12 Hevert Depot\n- 6 Amp. Pascorbin 750 mg/5 ml\n- 1 Amp. Tonico Injeel Heel\n- 250 ml NaCl 0,9 %\n\n**Frequenz:** 1–2× / Woche über 3–5 Wochen\n**Dauer der Infusion:** 45 min\n\n### 2. Orale Medikation\nJe nach Labor Auffüllen von Vitaminen / Mineralstoffen:\n- **Vitaplace Vit. D3** Tropfen nach Bedarf\n- **Vitaplace Q10 + NADH Energy Kapseln:** 1-1-0 bis 2-2-0, jeweils 15 min vor dem Essen einnehmen, **keine Milchprodukte!**\n- **Vitaplace Magnesium Energy Booster Pulver:** 1–2 Messlöffel Pulver tgl. mit Wasser'
),
(
  'Vitaplace Infusion Tinnitus – Therapieprotokoll',
  'Naturheilpraxis Peter Rauch > Vitaplace > Therapieprotokolle',
  ARRAY['vitaplace','infusion','tinnitus','ohrgeräusche','durchblutung','ginkgo','magnesium','b-vitamine','memo','therapieprotokoll'],
  E'## Therapieprotokoll Tinnitus\n\n**Name der Infusion:** Vitaplace Infusion Tinnitus\n\n### 1. Infusion\n- 1 Amp. Spascupreel Heel\n- 1 Amp. Graphites Homaccord Heel\n- 1 Amp. Circulo Inj. Heel\n- 1 Amp. Veno Injektopas Pascoe\n- 1 Amp. Ginkgo Loges\n- 1 Amp. Magnesiocard Verla 72,9 mg Mg\n- 1 Amp. Folsäure Hevert 5 mg\n- 1 Amp. Vit. B1 Hevert 200 mg\n- 1 Amp. Vit. B6 Hevert 50 mg\n- 1 Amp. Vit. B12 Depot Hevert 1000 µg\n- 250 ml NaCl 0,9 %\n\n**Frequenz:** 2× / Woche über 5 Wochen je nach Verlauf\n**Dauer der Infusion:** 45 min\n**Hinweis:** langsam infundieren wegen Kreislaufstabilität / Magnesiumflash\n\n### 2. Orale Medikation\n- **Vitaplace Komplex MEMO:** 3× 30–40 Tro. täglich\n- **Vitaplace MemoFit Kps:** 3× 1 Kps. täglich'
),
(
  'Vitaplace Stress Balance Kapseln',
  'Naturheilpraxis Peter Rauch > Vitaplace > Nahrungsergänzungsmittel',
  ARRAY['vitaplace','stress','stress-balance','kapseln','aminosäuren','b-vitamine','tagsüber','beruhigung','phenylalanin','tryptophan','nahrungsergänzung'],
  E'## Stress Balance Kapseln\n\n### Therapeuteninformation\nZum Ausgleich von Stresszuständen.\n\n**Hinweise / Kontraindikationen:**\n- Bei Einnahme von Antidepressiva vor dem Verzehr Rücksprache mit Heilpraktiker oder Arzt halten.\n- Nach Einnahme ist die Fähigkeit zur Teilnahme am Straßenverkehr möglicherweise beeinträchtigt.\n- Enthält **Phenylalanin** — nicht bei Phenylketonurie einnehmen.\n- Nicht für Schwangere, Stillende, Jugendliche und Kinder geeignet.\n\n### Dosierung\nTagsüber 2 Kapseln einnehmen. Die empfohlene tägliche Verzehrempfehlung darf nicht überschritten werden.\nNahrungsergänzungsmittel — kein Ersatz für ausgewogene Ernährung und gesunde Lebensweise.\n\n### Tipp\nTherapieoptimierung durch Kombination mit **Vitaplace Komplex GNt** oder **Vitaplace Komplex RELaku**.\n\n### Zusammensetzung (2 Kapseln) und biochemischer Effekt\n| Inhaltsstoff | Menge | Wirkung |\n|---|---|---|\n| Cordyceps sinensis (Schlauchpilz) | 100 mg | ernährungsphysiologische Funktionen |\n| Folsäure | 400 µg | normale Aminosäuresynthese, Verringerung von Müdigkeit |\n| Granatapfelextrakt | 100 mg | antioxidativ, schützt vor Zellschäden durch freie Radikale |\n| L-Arginin | 200 mg | Vorstufe von Stickstoffmonoxid (NO, Botenstoff) |\n| L-Lysin | 50 mg | essentielle Aminosäure |\n| L-Phenylalanin | 400 mg | essentielle Aminosäure |\n| L-Tryptophan | 200 mg | essentielle Aminosäure |\n| Pantothensäure | 90 mg | Synthese/Stoffwechsel von Neurotransmittern, geistige Leistung |\n| Riboflavin (B2) | 14 mg | Energieproduktion, normale Funktion des Nervensystems |\n| Thiamin (B1) | 11 mg | Verringerung von Müdigkeit und Ermüdung |\n| Vitamin B12 | 100 µg | Nervenfunktion, Eiweißstoffwechsel |\n| Vitamin B6 | 20 mg | Nervenfunktion, Eiweißstoffwechsel |'
),
(
  'Vitaplace Day Relax Kapseln',
  'Naturheilpraxis Peter Rauch > Vitaplace > Nahrungsergänzungsmittel',
  ARRAY['vitaplace','day-relax','tagsüber','entspannung','nervenkraft','belastbarkeit','same','rhodiola','griffonia','vitaresorp','nahrungsergänzung'],
  E'## Day Relax Kapseln\n\n### Therapeuteninformation\nEin Komplex aus bewährten Vitaminen, Mineral- und Pflanzenstoffen für bessere Nervenkraft, Entspannung und stärkere Belastbarkeit tagsüber.\n\nDie **Vitaresorp®-Technologie** sorgt durch verbesserte Resorption dafür, dass die wertvollen Mineralien und Nährstoffe gezielter und in größerer Menge in den Stoffwechsel und an die gewünschten Wirkorte im Körper gelangen.\n\n### Dosierung\nTäglich **2 transparente Kapseln + 1 rote Kapsel** einnehmen.\n\n### Tipp\n**Vitaplace Day Relax** in Kombination mit **Vitaplace Night Relax** — aufeinander abgestimmte Produkte, deren Inhaltsstoffe sich gegenseitig verstärken.\n\n### Zusammensetzung pro Tagesdosis\n| Inhaltsstoff | 2 transparente Kps | 1 rote Kps | gesamt / Tag | % NRV* |\n|---|---|---|---|---|\n| Distelöl | 250 mg | — | 250 mg | ** |\n| Folsäure | 670 µg | — | 670 µg | 330 % |\n| Ginseng-Wurzel-Extrakt | 50 mg | — | 50 mg | ** |\n| Griffonia simplicifolia Samen-Extrakt | 150 mg | 214 mg | 264 mg | ** |\n| Grüner Tee-Extrakt | 100 mg | — | 100 mg | ** |\n| Kokosöl | 200 mg | — | 200 mg | ** |\n| Kupfer | 0,5 mg | — | 0,5 mg | 50 % |\n| Magnesium | 210 mg | — | 210 mg | 56 % |\n| Niacin | 60 mg | — | 60 mg | 375 % |\n| Pantothensäure | 24 mg | — | 24 mg | 600 % |\n| Rhodiola Rosea-Extrakt | 50 mg | — | 50 mg | ** |\n| S-Adenosyl-Methionin (SAMe) | 100 mg | 50 mg | 150 mg | ** |\n| Sonnenblumenlecithin | 65 mg | — | 65 mg | ** |\n| Thiamin | 12 mg | — | 12 mg | 1091 % |\n| Vitamin B12 | 100 µg | — | 100 µg | 4000 % |\n| Vitamin B6 | 12 mg | — | 12 mg | 857 % |\n| Vitamin C | 25 mg | — | 25 mg | 30 % |\n| Vitamin D3 | 25 µg | — | 25 µg | 500 % |\n\n\\* % NRV = Nährstoffbezugswert für die tägliche Zufuhr (Verordnung (EU) Nr. 1169/2011)\n\\*\\* kein NRV festgelegt'
);